### ISSUE TITLE
AttributeError: 'Request' object has no attribute 'session'

### ISSUE THREAD

**Issue by d3cline** [omarbenhamid/django-mcp-server#9]
Had things kinda working on the git checkout between 0.4.0 and 0.5.1 but lo and behold i patched today to the latest and now I have this. 
I am using sessions, so i dunno why it is saying this. ChatGPT had some suggestions, but none of them panned out. it smells like a bug to me, should be able to run stateless for testing. Before I go trying to patch this into oblivion, any idea why it thinks request has no session? I do plan on using token auth eventually, but as of right now thats is disabled. 

```
Traceback (most recent call last):
  File "/home/control/env_313/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/control/env_313/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/control/env_313/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/control/env_313/lib/python3.13/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/control/env_313/lib/python3.13/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/control/env_313/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/control/env_313/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/control/env_313/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/control/env_313/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/control/env_313/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/control/env_313/lib/python3.13/site-packages/mcp_server/views.py", line 18, in get
    return self.mcp_server.handle_django_request(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/control/env_313/lib/python3.13/site-packages/mcp_server/djangomcp.py", line 207, in handle_django_request
    delattr(request, 'session')
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'session'

```

**Comment by d3cline** [comment]
Django version. The line in the middleware that matters, unless you know of any other ones I should be looking at in particular. 


```
>>> print(django.VERSION)
(4, 1, 2, 'final', 0)
>>> 



MIDDLEWARE = [
...
    'django.contrib.sessions.middleware.SessionMiddleware',
...
]


ERROR 2025-05-28 15:49:52,566 193 djangomcp 🌀 Request instance: <rest_framework.request.Request: GET '/mcp'>
ERROR 2025-05-28 15:49:52,567 194 djangomcp 🌀 Request class:    <class 'rest_framework.request.Request'>
ERROR 2025-05-28 15:49:52,567 195 djangomcp 🌀 Module:           rest_framework.request
ERROR 2025-05-28 15:49:52,567 198 djangomcp 🌀 Source file:      /home/control/env_313/lib/python3.13/site-packages/rest_framework/request.py
ERROR 2025-05-28 15:49:52,572 203 djangomcp 🌀 Class source:
```

seems it thinks its a DRF endpoint, I am using DRF validation, or was, right now all token auth is disabled. But beyond this its a standard django app, and I followed the instructions in the readme, the module is from pypi and only has the above modification so I could continue to debug.

**Comment by d3cline** [comment]
seems it was a warning, but it can be suppressed with in the view
```
from drf_spectacular.utils import extend_schema, extend_schema_view

@extend_schema_view(
    get=extend_schema(exclude=True),
    post=extend_schema(exclude=True),
    delete=extend_schema(exclude=True),
)
```

**Comment by omarbenhamid** [comment]
What is django for if not doing clean and mature apps 👍 

>   File "/home/control/env_313/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 698, in _map_serializer_field
>     if isinstance(field, (serializers.BooleanField, serializers.NullBooleanField)):
>                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The spectacular error is due to DRF version mismatch : NullBooleanFieald has been [deprecated in 3.12](https://www.django-rest-framework.org/community/release-notes/#3120) and Django MCP Server requires (and is tested with) DRF 3.15.0 . 

If you DRF earlier that 3.12.0 the map_serializer method is probably not published yet so MCP Server will not be able to generate JSONSchema from serializer. It will normally log a warning asking you to document your schema manually in instructions.

> AttributeError: 'Request' object has no attribute 'session'

For the original problem: it is probably the same origin. Works well on 3.15 but I guess in older versions of DRF Request.session was not a properly definied attribute (may be mocked with __getattribute__ or something ?)


What version of DRF do you use ? Will you be able to move to 3.15 ?

**Comment by d3cline** [comment]
thanks, I have been in dependency hell with my app trying to get it to 3.15, thank you for identifying the error. I was on 3.14, not 3.12, but I will take it. I will be able to test this proper in a few days when my flight lands. I do also have an example for using the shcema generated by swagger docs to feed into this, if you would like to include that as an example, I think it might be useful for other users. Thanks for your work, please leave the ticket open for a few days so I can have some time to isolate and document this for any future travelers. I did end up having to settle on a combo of like, 
Django 4.1.2, DRF 3.16 which it doesn't really like, but works, and swagger i think 0.28, if anyone lands here before testing.

**Comment by omarbenhamid** [comment]
Can you explain more what you are trying to do with swagger ?

As of today, if you use DRF 3.15 the JSONSchema of the input parameters is autogenerated and included in your MCP description if your APIView uses the standard `serializer_class` parameter to set a serializer. May be you have another approach in your API ? And by the way, you do not need dependency to spectacular for this in recent DRF to do this.

**Comment by d3cline** [comment]
Sure, we are a web hosting company. So the idea of our SaaS is to provide friendly endpoints for various objects. We have had a mature Django app for a long time. And a mature JSON API based on DRF. I did read the docs about the serializes, but the problem is this is still possible to leak data, or expose our business logic in some uncanny way. Its far easier for us to just expose and document our JSON api to an LLM. I have some experience with LLMs and a lot with ChatGPT but almost none with Claude. We are adding the feature to be in line with industry standards and adoption of various AI. I have wrapped the swagger schema into an openAI compliant tooling JSON. The idea is to be as ready as possible, without creating a whole new attack surface. For our service, a keyed api based SaaS where it really does matter 'who' you are, provision of hardware, billing, etc. there is no reason to give an LLM more access beyond the JSON api, for now. I would love to imagine an agent who could use our service to boostrap an entire website or various configs, but is that practical right now, how would I even begin to do unit tests for that, etc...

**Comment by d3cline** [comment]
some other issues i have thought about but honestly don't know the answer too would be the concept that say I have the JSON api documented, I tell the LLM my token so it has that loaded into context. An LLM SaaS like claude.ai or chatGPT's web app can't make outbound json calls, a desktop app in theory could, but do they? Would the LLM be only able to provision hardware via a python script, which isn't as seamless as I would like this experience to be for the end user at the end of the day. And as I mention, testing seems very difficult if i wanted to expose things at a lower level. The need for a streaming server, for our objects which have a status based on if they are provisioned or not, seems like a hard problem to solve. I might want to add a webhook, if this was a normal API, but will this standard adopt webhooks? IF its not a websocket, how would that work? If we have a session we can be stateless, but this still requires the client to be connected and pinging every X seconds, very sloppy. So I am not sure if the protocol, let alone the module is anywhere near this or if this is a bad expectation of a final UX on this kind of stack.

**Comment by omarbenhamid** [comment]
Ok, I see a little better.

**Can an LLM call a JSON over HTTP ?**

Technically yes : you can provide a "call_http" MCP tool which takes method, url, headers, body as parameters. The LLM could use it to make a HTTP call. Now notice that this is quite abstract as tool, I guess that higher end LLMs and reasoning models can use it, but cheaper ones will probably have trouble, because the planning is more complex : LLMs are trained to understand, choose and use tools but you will need to prompt your LLM to understand, and choose an API then to use the "call_api" tool to call it. I guess higher end reasoning LLMs can do good with it.

Notice thow that you can directly feed OpenAPI specs into OpenAI's custom GPTs and they manage to call it but you will need to setup oauth. I used it on some projects with DRF + django-oauth-toolkit, and it works very well.

**Can you manage long running tasks like creating a server ?**

The issue is not the LLM but the user interface : in Chat interfaces of course the LLM expects the answer immediately as it needs to "answer the user". If you use agentic frameworks or integration plateforms (like n8n or so) you can interact between LLM and long running processes with no difficulties. Then you could use polling or WebSockets depending on how immediate you need the reaction.

**Comment by omarbenhamid** [comment]
I will keep this issue open for a couple of days, but I will need to close it if your issue is solved.

**Comment by d3cline** [comment]
I can verify this is still 'broken' or at least 'unsupported' on the versions of Django and DRF I outlined, 

```
Django                        4.1.2
djangorestframework           3.16.0
```

With the patch I supplied it works. If we can't get it to backport here in the main repo I will have to fork it. That is OK tho, at least its reported. TLDR older versions of Django, buyer beware. 

I am prob going to write a middleware which does MCP in the end, and it can do some of the tasks you are talking about. Thanks for all the feedback.

**Comment by d3cline** [comment]
will keep digging, thanks.

**Comment by omarbenhamid** [comment]
**The short answer :** Ok for safeguarding with hasattr (without the try: / except AttributeError:). Does this fix your issue ?

If so do you want to send a PR or I push it in next release ?

**The longer one: ** o3 oversights the existance of django's session middleware which always creates the `request.session` object AFAIK.  What was wierd with your bug is that the AttributeError was raised by `delattr()` call wheras `request.session.save()` and `request.session.session_key` in the two lines before do not raise any Exception ... 

By the way I like the term **"surgical patch"**  we hate it but forced to use it sometimes ...

**Comment by d3cline** [comment]
thanks again.
